spring:
  application:
     name: ms-naissances
  jpa:
     hibernate:
       ddl-auto: validate
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /api
    port: 40082

rsa:
  rsa-private-key: classpath:certs/private.pem
  rsa-public-key:  classpath:certs/public.pem