name: deploy application
run-name: ${{ github.actor }} is deploying project 🚀

on:
  push:
  workflow_dispatch:

jobs:
  create-folder:
    name: Create folder on server
    runs-on: ubuntu-latest
    steps:
      - name: execute remote ssh commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build project
        run: |
          ./mvnw clean package spring-boot:repackage -Dmaven.test.skip=true
          ls -al target
