    name: deploy application
    run-name: ${{ github.actor }} is deploying project back_end 🚀
    on:
       push:
       workflow_dispatch:
    env:
      GROUP: /opt/serge-mane
      PROJECT: ms-naissances
    jobs:
      create-folder:
        name: Create folder on server
        runs-on: ubuntu-latest
        steps:
          - name: Execute remote SSH commands
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.SERVER_HOST }}
              port: ${{ secrets.SERVER_PORT }}
              username: ${{ secrets.SERVER_USERNAME }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                 sudo mkdir -p ${{env.GROUP}}/${{env.PROJECT}}
      build-project:
        needs: create-folder
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
          - name: Setup java version
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '21'

          - name: Make mvnw executable
            run: chmod +x mvnw

          - name: build project
            run: |
              ./mvnw clean package spring-boot:repackage -Dmaven.test.skip=true

          - name: rename project
            run: |
              mv target/${{env.PROJECT}}-*.jar target/${{env.PROJECT}}.jar

          - name: copy file on server
            uses: appleboy/scp-action@v1
            with:
              host: ${{ secrets.SERVER_HOST }}
              port: ${{ secrets.SERVER_PORT }}
              username: ${{ secrets.SERVER_USERNAME }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              source: target/${{env.PROJECT}}.jar
              target: ${{env.GROUP}}/${{env.PROJECT}}
              strip_components: 1
              overwrite: true
      run-project:
          name: executing project on the server
          runs-on: ubuntu-latest
          needs: build-project
          steps:
            - name: Execute remote SSH commands
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SERVER_HOST }}
                port: ${{ secrets.SERVER_PORT }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  ln -sf ${{env.GROUP}}/${{env.PROJECT}}/${{env.PROJECT}}.jar /etc/init.d/${{env.PROJECT}}
                  sudo /etc/init.d/${{env.PROJECT}} stop
                  sudo /etc/init.d/${{env.PROJECT}} start --spring.mail.host=${{secrets.MAIL_HOST}} --spring.datasource.username=${{secrets.DATABASE_USERNAME}} --spring.datasource.password=${{secrets.DATABASE_USERPASSWORD}} --spring.datasource.url=${{secrets.DATABASE_URL}} --spring.sql.init.mode=always

