name: Deploy Application
run-name: ${{ github.actor }} is deploying project 🚀
on:
  push:
  workflow_dispatch:
jobs:
  Create-folder:
    name: Create Folder on Server
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username:  ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p /opt/serge-mane/ms-serge-mane
  build-project:
    runs-on: ubuntu-latest
    needs: Create-folder
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: build project
        run: |
          ./mvnw clean package spring-boot:repackage -Dmaven.test.skip=true
          ls -al target
      - name: Rename project
        run: |
          mv target/ms-naissances-*.jar target/ms-naissances.jar
      - name: Copy files on sever
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: target/ms-naissances.jar
          target: /opt/serge-mane/ms-serge-mane
          strip_components: 1
          overwrite: true
  run-project:
    name: Create Folder on Server
    needs: build-project
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            #!/bin/bash
            case "$1" in
              start)
                echo "Starting ms-naissances"
                nohup java -jar /opt/serge-mane/ms-serge-mane/ms-naissances.jar \
                  --spring.mail.host=${MAIL_HOST} \
                  --spring.datasource.username=${DATABASE_USERNAME} \
                  --spring.datasource.password=${DATABASE_USERPASSWORD} \
                  --spring.datasource.url=${DATABASE_URL} \
                  --spring.sql.init.mode=always &
                ;;
              stop)
                echo "Stopping ms-naissances"
                pkill -f ms-naissances.jar
                ;;
              *)
                echo "Usage: $0 {start|stop}"
                exit 1
            esac
